### ISSUE TITLE
translations are failing to submit to the babel repo due to TCP.close event

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#114]
@oliver-phet received an email from a translator who is having issues with submitting translations.  An examination of Rosetta's log reveals multiple instances of the following error:

```
2016-01-25T02:46:23.458Z - info: queuing string submission for friction_fr
Error: request aborted
     at makeError (/data/share/phet/phet-repos/rosetta/node_modules/body-parser/node_modules/raw-body/index.js:156:15)
     at IncomingMessage.onAborted (/data/share/phet/phet-repos/rosetta/node_modules/body-parser/node_modules/raw-body/index.js:254:10)
     at IncomingMessage.emit (events.js:92:17)
     at abortIncoming (http.js:1915:11)
     at Socket.serverSocketCloseListener (http.js:1927:5)
     at Socket.emit (events.js:117:20)
     at TCP.close (net.js:465:12)
```

When I look through the code, it appears that this error is occurring when the `commitQueue` tries to commit to babel, but details are scant.  I'm not sure why such errors would occur, or why the didn't occur in the past.  More investigation is required.

**Comment by jbphet** [comment]
I did an ```npm update```in Rosetta's directory on figaro, pulled the changes for additional debug statements, and restarted Rosetta.  I then asked @oliver-phet to contact one of the translators whose attempt to submit a translation failed.  That translator attempted a translation overnight, and it worked.  It may be that something in the GitHub API changed and we needed an updated ```octonode``` package, and that fixed things.  Hard to say.  I discussed this with @jonathanolson, and we agreed that we should at least try to send an email in the future when this error occurs.

**Comment by jbphet** [comment]
An examination of the log where the latest translation occurred still shows an error message when Rosetta tries to commit the joist strings immediately after commiting the friction strings.  It retries, then succeeds.  I should dig into this more too, and see if I can determine what the failure is.

```
2016-01-26T01:46:24.784Z - info: attempting commit for file = friction/friction-strings_fr.json
2016-01-26T01:46:24.790Z - info: attempting commit for file = joist/joist-strings_fr.json
2016-01-26T01:46:25.082Z - info: found file friction/friction-strings_fr.json in GitHub.  Attempting to update.
2016-01-26T01:46:25.094Z - info: found file joist/joist-strings_fr.json in GitHub.  Attempting to update.
2016-01-26T01:46:25.436Z - info: commit: "1453772784784 automated commit from rosetta for file friction/friction-strings_fr.json" committed successfully
2016-01-26T01:46:25.456Z - error: Error: Repo updateContents error. Error committing to file joist/joist-strings_fr.json. Trying again in 5 seconds...
2016-01-26T01:46:30.821Z - info: found file joist/joist-strings_fr.json in GitHub.  Attempting to update.
2016-01-26T01:46:31.371Z - info: commit: "1453772784790 automated commit from rosetta for file joist/joist-strings_fr.json" committed successfully
```

**Comment by jbphet** [comment]
I just check through the latest log, and this error is not appearing anymore.  My guess is that this behavior is closely related to #105 since the symptoms sound essentially the same, and this was just a particular way in which the GitHub interaction was failing.  I'm going to close this issue and track the work related to GitHub interaction under #105.
