### ISSUE TITLE
TypeError: response.render is not a function

### ISSUE THREAD

**Issue by muedli** [phetsims/rosetta#250]
When a user logs in, Rosetta sometimes crashes and restarts. We see the error in the title when this happens. We think this issue goes away if you clear cookies.

**Comment by muedli** [comment]
OK, I think I’ve figured it out. It looks like someone who was neither a trusted translator nor a team member tried to access the translate page. (See line 161 in routeHandlers.js.) When this is the case, we call the renderError function. The renderError function is defined in the TranslationUtils.js module. It takes a response, message, and error. We use renderError to render the error (go figure) by using response.render. The error we’re getting is “response.render is not a function”.

**Comment by muedli** [comment]
## Steps to Reproduce

1. Switch to 1f735de98e224d2981f288db85ff0bef185a249a.
2. Try to log in using one of the QA accounts that isn't a team member or a trusted translator.
3. You should see a 503 error.

![503](https://user-images.githubusercontent.com/60749003/104798070-d2dc1080-5780-11eb-8c73-a80e3874739f.png)

### Logs

```
Jan 15 22:22:40 phet-server-dev.int.colorado.edu rosetta[10531]: info - Host is ox-dev.colorado.edu.
Jan 15 22:22:40 phet-server-dev.int.colorado.edu rosetta[10531]: info - Request URL is /translate/.
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: info - Checking for login cookie.
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: info - Valid session cookie exists. User ID is undefined.
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: info - Data: { "username": "Phet", "userId": 797374, "email": "phet.qa.1@gmail.com", "loggedIn": true, "teamMember": false, "trustedTranslator": false }.
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: info - Credentials obtained. User is logged in. Moving to next step.
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: /data/share/phet/rosetta/js/TranslationUtils.js:96
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: response.render( 'error.html', {
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: ^
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: TypeError: response.render is not a function
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: at renderError (/data/share/phet/rosetta/js/TranslationUtils.js:96:12)
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: at IncomingMessage.<anonymous> (/data/share/phet/rosetta/js/routeHandlers.js:161:13)
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: at IncomingMessage.emit (events.js:326:22)
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: at endReadableNT (_stream_readable.js:1241:12)
Jan 15 22:22:56 phet-server-dev.int.colorado.edu rosetta[10531]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
Jan 15 22:22:57 phet-server-dev.int.colorado.edu rosetta[10999]: info - ========== Rosetta is starting up! ==========
```

**Comment by muedli** [comment]
I'm not exactly sure why this is happening, but I rewrote the checkForValidSession function in routeHandlers.js that seemed to be the root of the problem in https://github.com/phetsims/rosetta/issues/251.

**Comment by muedli** [comment]
We are fairly certain that my rewrite has solved this issue. Closing.
