### ISSUE TITLE
Submitting translation causes `PayLoadTooLargeError`

### ISSUE THREAD

**Issue by liammulh** [phetsims/rosetta#309]
1. Select Acid-Base Solutions
2. Select Abkhazian (ab)
3. Click the Go button
4. Click the submit button

You should see:

```
PayloadTooLargeError: request entity too large
    at readStream (/Users/liam/Code/l/phet/rosetta/node_modules/raw-body/index.js:156:17)
    at getRawBody (/Users/liam/Code/l/phet/rosetta/node_modules/raw-body/index.js:109:12)
    at read (/Users/liam/Code/l/phet/rosetta/node_modules/body-parser/lib/read.js:79:3)
    at urlencodedParser (/Users/liam/Code/l/phet/rosetta/node_modules/body-parser/lib/types/urlencoded.js:116:5)
    at Layer.handle [as handle_request] (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:328:13)
    at /Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/Users/liam/Code/l/phet/rosetta/node_modules/body-parser/lib/types/json.js:119:7)
    at Layer.handle [as handle_request] (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:328:13)
    at /Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/liam/Code/l/phet/rosetta/node_modules/express/lib/router/index.js:280:10)
    at Immediate.<anonymous> (/Users/liam/Code/l/phet/rosetta/node_modules/express-session/index.js:506:7)
```

**Comment by liammulh** [comment]
# Investigation

Relevant SO Issues:
* https://stackoverflow.com/questions/36716311/node-js-error-too-many-parameters-error-while-uploading-bulk-data
* https://stackoverflow.com/questions/19917401/error-request-entity-too-large

**Comment by liammulh** [comment]
I reset my local copy of rosetta to:

```
commit efe7727aa839fdbec5baa70c99b7e998d896d87a (HEAD -> master)
Author: Liam Mulhall <muedli.liam@gmail.com>
Date:   Fri Jan 1 11:31:13 2021 -0700

    Changing 'Off Line' to 'Offline'.
```

and I'm still seeing this error.

**Comment by liammulh** [comment]
I might (?) have fixed this.

**Comment by liammulh** [comment]
https://github.com/phetsims/rosetta/commit/67cbb476b251c72670faebb7857e944391c015a1 seems to have fixed the issue on my macOS machine. I still don't understand why we had the issue in the first place.

**Comment by liammulh** [comment]
Closing.
